### ISSUE TITLE
Estimate age realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [zonetrooper32/AgeEstimateAdience#1]
How do i estimate the age realtime?

**Comment by cjiang2** [comment]
I'll update all the scripts including detailed training protocols, optimizers and predictions soon, but might take a few days since I'm too busy these days working on another project.
However idea for real-time prediction is simple, you load back the pre-trained model with tensorflow saver operation, perform face detection with Haar Cascade module from OpenCV, then use tensorflow and feed the cropped face into model and thus get the prediction.

**Comment by Zumbalamambo** [comment]
Okay thank you
